-- ============================================================================
-- Source a real profanity/offensive-terms list for reserved_usernames
-- ============================================================================
-- Populates reserved_usernames with the LDNOOBW English list (List of
-- Dirty, Naughty, Obscene, and Otherwise Bad Words — an established,
-- widely-reused, permissively-licensed word list maintained on GitHub:
-- github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words,
-- 276 single-word entries after filtering out multi-word phrases,
-- which can never match a single dot/underscore-delimited username segment
-- anyway. Sourced from that project rather than hand-written, per the
-- reasoning in 20260710000008_username_rules.sql's header.
--
-- This also switches is_username_allowed() from substring (ILIKE) matching
-- to exact-segment matching. Substring matching against a list this size
-- would false-positive constantly on completely innocent usernames that
-- merely CONTAIN a banned term inside a longer word — the classic
-- "Scunthorpe problem" (e.g. a short banned word appearing inside a much
-- longer, innocuous one). Splitting the candidate on '.' and '_' (the
-- only separators a username can contain) and requiring an EXACT match
-- against a segment avoids that almost entirely, at the cost of not
-- catching someone who deliberately jams a banned word into a longer
-- token with no separators — an acceptable trade favoring far fewer
-- false positives for real users.
-- ============================================================================

insert into public.reserved_usernames (term) values
  ('2g1c'),
  ('acrotomophilia'),
  ('anal'),
  ('anilingus'),
  ('anus'),
  ('apeshit'),
  ('arsehole'),
  ('ass'),
  ('asshole'),
  ('assmunch'),
  ('autoerotic'),
  ('babeland'),
  ('bangbros'),
  ('bangbus'),
  ('bareback'),
  ('barenaked'),
  ('bastard'),
  ('bastardo'),
  ('bastinado'),
  ('bbw'),
  ('bdsm'),
  ('beaner'),
  ('beaners'),
  ('beastiality'),
  ('bestiality'),
  ('bimbos'),
  ('birdlock'),
  ('bitch'),
  ('bitches'),
  ('blowjob'),
  ('blumpkin'),
  ('bollocks'),
  ('bondage'),
  ('boner'),
  ('boob'),
  ('boobs'),
  ('bukkake'),
  ('bulldyke'),
  ('bullshit'),
  ('bunghole'),
  ('busty'),
  ('butt'),
  ('buttcheeks'),
  ('butthole'),
  ('camgirl'),
  ('camslut'),
  ('camwhore'),
  ('carpetmuncher'),
  ('cialis'),
  ('circlejerk'),
  ('clit'),
  ('clitoris'),
  ('clusterfuck'),
  ('cock'),
  ('cocks'),
  ('coon'),
  ('coons'),
  ('coprolagnia'),
  ('coprophilia'),
  ('cornhole'),
  ('creampie'),
  ('cum'),
  ('cumming'),
  ('cumshot'),
  ('cumshots'),
  ('cunnilingus'),
  ('cunt'),
  ('darkie'),
  ('daterape'),
  ('deepthroat'),
  ('dendrophilia'),
  ('dick'),
  ('dildo'),
  ('dingleberries'),
  ('dingleberry'),
  ('doggiestyle'),
  ('doggystyle'),
  ('dolcett'),
  ('domination'),
  ('dominatrix'),
  ('dommes'),
  ('dvda'),
  ('ecchi'),
  ('ejaculation'),
  ('erotic'),
  ('erotism'),
  ('escort'),
  ('eunuch'),
  ('fag'),
  ('faggot'),
  ('fecal'),
  ('felch'),
  ('fellatio'),
  ('feltch'),
  ('femdom'),
  ('figging'),
  ('fingerbang'),
  ('fingering'),
  ('fisting'),
  ('footjob'),
  ('frotting'),
  ('fuck'),
  ('fuckin'),
  ('fucking'),
  ('fucktards'),
  ('fudgepacker'),
  ('futanari'),
  ('gangbang'),
  ('genitals'),
  ('goatcx'),
  ('goatse'),
  ('gokkun'),
  ('goodpoop'),
  ('goregasm'),
  ('grope'),
  ('guro'),
  ('handjob'),
  ('hardcore'),
  ('hentai'),
  ('homoerotic'),
  ('honkey'),
  ('hooker'),
  ('horny'),
  ('humping'),
  ('incest'),
  ('intercourse'),
  ('jailbait'),
  ('jigaboo'),
  ('jiggaboo'),
  ('jiggerboo'),
  ('jizz'),
  ('juggs'),
  ('kike'),
  ('kinbaku'),
  ('kinkster'),
  ('kinky'),
  ('knobbing'),
  ('livesex'),
  ('lolita'),
  ('lovemaking'),
  ('masturbate'),
  ('masturbating'),
  ('masturbation'),
  ('milf'),
  ('mong'),
  ('motherfucker'),
  ('muffdiving'),
  ('nambla'),
  ('nawashi'),
  ('negro'),
  ('neonazi'),
  ('nigga'),
  ('nigger'),
  ('nimphomania'),
  ('nipple'),
  ('nipples'),
  ('nsfw'),
  ('nude'),
  ('nudity'),
  ('nutten'),
  ('nympho'),
  ('nymphomania'),
  ('octopussy'),
  ('omorashi'),
  ('orgasm'),
  ('orgy'),
  ('paedophile'),
  ('paki'),
  ('panties'),
  ('panty'),
  ('pedobear'),
  ('pedophile'),
  ('pegging'),
  ('penis'),
  ('pikey'),
  ('pissing'),
  ('pisspig'),
  ('playboy'),
  ('ponyplay'),
  ('poof'),
  ('poon'),
  ('poontang'),
  ('poopchute'),
  ('porn'),
  ('porno'),
  ('pornography'),
  ('pthc'),
  ('pubes'),
  ('punany'),
  ('pussy'),
  ('queaf'),
  ('queef'),
  ('quim'),
  ('raghead'),
  ('rape'),
  ('raping'),
  ('rapist'),
  ('rectum'),
  ('rimjob'),
  ('rimming'),
  ('sadism'),
  ('santorum'),
  ('scat'),
  ('schlong'),
  ('scissoring'),
  ('semen'),
  ('sex'),
  ('sexcam'),
  ('sexo'),
  ('sexual'),
  ('sexuality'),
  ('sexually'),
  ('sexy'),
  ('shemale'),
  ('shibari'),
  ('shit'),
  ('shitblimp'),
  ('shitty'),
  ('shota'),
  ('shrimping'),
  ('skeet'),
  ('slanteye'),
  ('slut'),
  ('smut'),
  ('snatch'),
  ('snowballing'),
  ('sodomize'),
  ('sodomy'),
  ('spastic'),
  ('spic'),
  ('splooge'),
  ('spooge'),
  ('spunk'),
  ('strapon'),
  ('strappado'),
  ('suck'),
  ('sucks'),
  ('swastika'),
  ('swinger'),
  ('threesome'),
  ('throating'),
  ('thumbzilla'),
  ('tit'),
  ('tits'),
  ('titties'),
  ('titty'),
  ('topless'),
  ('tosser'),
  ('towelhead'),
  ('tranny'),
  ('tribadism'),
  ('tubgirl'),
  ('tushy'),
  ('twat'),
  ('twink'),
  ('twinkie'),
  ('undressing'),
  ('upskirt'),
  ('urophilia'),
  ('vagina'),
  ('viagra'),
  ('vibrator'),
  ('vorarephilia'),
  ('voyeur'),
  ('voyeurweb'),
  ('voyuer'),
  ('vulva'),
  ('wank'),
  ('wetback'),
  ('whore'),
  ('worldsex'),
  ('xx'),
  ('xxx'),
  ('yaoi'),
  ('yiffy'),
  ('zoophilia')
on conflict (term) do nothing;

create or replace function public.is_username_allowed(candidate text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  seg text;
begin
  foreach seg in array regexp_split_to_array(candidate, '[._]') loop
    if seg <> '' and exists (select 1 from public.reserved_usernames where term = seg) then
      return false;
    end if;
  end loop;
  return true;
end;
$$;
